---
image: archlinux:latest

stages:
  - build
  - test
  - release

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  PACMAN_CACHE: "${CI_PROJECT_DIR}/.pacman/pkg"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

default:
  before_script:
    - pacman-key --init
    - pacman -Sy --needed --noconfirm --cachedir "${PACMAN_CACHE}" archlinux-keyring
    - pacman -Su --needed --noconfirm --cachedir "${PACMAN_CACHE}" cargo-deny git rust gcc pkg-config make scdoc
  interruptible: true

cache:
  paths:
    - .cargo/
    - target/
    - .pacman/pkg
  key: ${CI_JOB_NAME}

build:
  stage: build
  needs: []
  script:
    - cargo build --release
  artifacts:
    paths:
      - target
    expire_in: 1 day

man:
  stage: build
  needs: []
  script:
    - make docs
  artifacts:
    paths:
      - contrib/man/arch-audit.1
    expire_in: 1 day

completions:
  stage: build
  needs:
    - build
  script:
    - make completions
  artifacts:
    paths:
      - target/completion/
    expire_in: 1 day

format:
  stage: test
  needs: []
  script:
    - cargo fmt --all -- --check

clippy:
  stage: test
  needs:
    - build
  script:
    - find . -name '*.rs' -exec touch {} +
    - cargo clippy --all -- -D warnings

check:
  stage: test
  needs:
    - build
  script:
    - cargo check --all --verbose --release

test:
  stage: test
  needs:
    - build
  script:
    - cargo test --all --verbose --release

install:
  stage: test
  needs:
    - build
  script:
    - install -d destdir
    - make DESTDIR=destdir PREFIX=/usr install
  artifacts:
    paths:
      - destdir
    expire_in: 1 day

deny:
  stage: test
  needs: []
  script:
    - pacman -Su --needed --noconfirm --cachedir "${PACMAN_CACHE}" cargo-deny
    - cargo deny check

test-publish:
  stage: test
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - cargo publish --dry-run

crates_publish:
  stage: release
  tags:
    - secure
  needs:
    - build
    - man
    - completions
    - format
    - clippy
    - check
    - test
    - install
    - deny
  dependencies: []
  rules:
    - if: '$CARGO_REGISTRY_TOKEN && $CI_COMMIT_TAG && $CI_PROJECT_PATH == "archlinux/arch-audit"'
  script:
    - cargo publish
